name: Govern-Console CI/CD
on:
  push:
    paths:
    - 'packages/govern-console/**'
    branches:
    - 'develop'
    - 'master'
    - 'feature'

env:
  working-directory: packages/govern-console

jobs:
  build-and-deploy-console:
    runs-on: ubuntu-latest
    container: fleek/create-react-app:node-15
    name: builds and deploys console
    steps:
      - uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Cache yarn modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: yarn-${{ hashFiles('yarn.lock') }}
        working-directory: ${{env.working-directory}}

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ${{env.working-directory}}

      - name: Build the app
        run: yarn build
        working-directory: ${{env.working-directory}}

      - name: activate rinkeby's fleek
        run: mv fleek/console.rinkeby.json .fleek.json
        if: github.ref == 'refs/heads/develop'
        working-directory: ${{env.working-directory}}

      - name: activate mainnet's fleek
        run: mv fleek/console.mainnet.json .fleek.json
        if: github.ref == 'refs/heads/master'
        working-directory: ${{env.working-directory}}

      - name: builds and deploys console
        id: deploy
        uses: fleekhq/action-deploy@v1
        with:
          apiKey: ${{ secrets.FLEEK_API_KEY }}
          workDir: ${{env.working-directory}}

  build-and-deploy-storybook:
    runs-on: ubuntu-latest
    container: fleek/create-react-app:node-15
    name: builds and deploys storybook
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Cache yarn modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: yarn-${{ hashFiles('yarn.lock') }}
        working-directory: ${{env.working-directory}}

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ${{env.working-directory}}

      - name: Build the storybook
        run: yarn build-storybook
        working-directory: ${{env.working-directory}}
         
      - name: activate rinkeby's fleek
        run: mv fleek/storybook.json .fleek.json
        working-directory: ${{env.working-directory}}

      - name: builds and deploys storybook
        id: deploy
        uses: fleekhq/action-deploy@v1
        with:
          apiKey: ${{ secrets.FLEEK_API_KEY }}
          workDir: ${{env.working-directory}}

