name: Govern-Console CI/CD
on:
  push:
    branches:
    - 'develop'
    - 'master'
    - 'feature'

env:
  working-directory: packages/govern-console

jobs:
  build-and-deploy-console:
    runs-on: ubuntu-latest
    container: fleek/create-react-app:node-15
    name: builds and deploys console
    steps:
      - uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Cache yarn modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: yarn-${{ hashFiles('yarn.lock') }}
        working-directory: ${{env.working-directory}}